Algoritmo "calcular numero real"
// Disciplina   : fundamentos de programação
// Professor   : Cris
// Descrição   : ler um número real e imprimir duas casas após a virgula do
//               resultado do quadrado
// Autor(a)    : Jose matheus oliveira cavalcante
// Data atual  : 09/11/2021
Var
num : real

Inicio
num <- 998.5115

num<-num*2
escreval("O quadrado de sse número é", num:2:2)


Fimalgoritmo

